name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Build
        run: go build -v ./...
  
  inception:
    runs-on: ubuntu-latest
    environment: dev
    needs: build # wait until build is done
    steps:
      - uses: actions/checkout@v3
      - uses: mdp/openobserve_github_action_logs@main
        with:
          openobserve_endpoint: ${{ secrets.dev.OPENOBSERVE_ENDPOINT }} 
          openobserve_username: ${{ secrets.dev.OPENOBSERVE_USERNAME }}
          openobserve_key: ${{ secrets.dev.OPENOBSERVE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


